### ISSUE TITLE
X11-session error after running build.sh for version 22.04 with 5.2.2

### ISSUE THREAD

**Issue by SameerShanbhogue** [pieper/SlicerDockers#6]
Hi 

I am getting below error after for version 22.04, build.sh getting completed without any issue. 

![image](https://github.com/pieper/SlicerDockers/assets/84760553/ccb3b453-0268-42f2-beb3-4a740da11140)

**Comment by pieper** [comment]
It would be great to update these dockerfiles to newer versions.  If you want to do that please create a fork and start trying to make a version that works.  Without the exact context and steps to reproduce there's nothing I can do with this report.

**Comment by bhatrana** [comment]
@pieper  Hi there, I am also trying to make a 3D Slicer image in Docker using your repo. I used your master branch to replicate the same version 5.0.3, no issue on image build but there is an issue on connection to X11.  Any suggestions ?

![image](https://github.com/pieper/SlicerDockers/assets/79718549/5a98bf44-88ea-4ddf-b522-08d15c07d50c)
